name: Update Daily Feed
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # We skip actions/setup-python and use the system python
      - name: Generate XML
        run: |
          python3 --version
          python3 generate_feed.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git add feed.xml
          git commit -m "Update daily nostalgia picks" || exit 0
          git push
